name: Full News Update

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v6.0
        with:
          modules-to-cache: PSOpenAI

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          ollama serve &
          sleep 10  # Wait for Ollama service to start

      - name: Pull Ollama model
        run: |
          ollama pull llama3.1
          sleep 10  # Wait for model to be ready

      - name: Run news update script
        shell: pwsh
        env:
          BRAVE_API_KEY: ${{ secrets.BRAVE_API_KEY }}
          GIST_PAT: ${{ secrets.GIST_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          BING_API_KEY: ${{ secrets.BING_API_KEY }}
        run: |
          # Import-Module ./.github/workflows/trending/trending.psm1
          # Set-TrendingTopic -ApiSource Both